spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}

  jpa:
    database: "POSTGRESQL"
    show-sql: true
    # generate-ddl: true
    #hibernate:
    #  ddl-auto: "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name="Salbum"

api:
  security:
    token:
      secret: ${secret_token_security}

musicbrainz:
  api_url: ${musicbrainz_api_url}

release_images:
  api_url: ${release_images_api_url}

spotify:
  client_secret: ${spotify_client_secret}
  client_id: ${spotify_client_id}
  api_url: ${spotify_api_url}

lastfm:
  client_key: ${last_fm_api_key}
  shared_secret: ${last_fm_shared_secret}
  api_url: ${last_fm_api_url}
#logging:
#  level:
#    root: DEBUG

#    com:
#      fasterxml:
#        jackson: DEBUG
#    org:
#      springframework:
#        security: DEBUG
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG # Opcional
